{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$ref": "#/definitions/terminal-keeper",
  „definicje”: {
    "terminal-keeper": {
      „typ”: „obiekt”,
      „dodatkowe właściwości”: fałsz,
      "właściwości": {
        "$schema": {
          „typ”: „ciąg”,
          "description": "Ścieżka schematu JSON."
        },
        "aktywny": {
          „typ”: „ciąg”,
          "domyślny": "domyślny",
          „description”: „Służy do określenia, której sesji użyć”.
        },
        "temat": {
          "wyliczenie": [
            "domyślny",
            "kałamarz",
            "chaos",
            "plemię",
            "ikonowy",
            "neon",
            "solaryzowany",
            "kostka do gry"
          ],
          „description”: „Motyw może automatycznie wybierać kolory/ikony lub ręcznie”.
        },
        "zachowajistniejąceterminale": {
          „typ”: „wartość logiczna”,
          „domyślne”: fałsz,
          "description": "Zachowaj istniejące terminale otwarte podczas wykonywania sesji."
        },
        "aktywuj przy uruchomieniu": {
          „typ”: „wartość logiczna”,
          „domyślne”: fałsz,
          „description”: „Aktywowano sesję podczas uruchamiania programu Visual Studio Code”.
        },
        "noClear": {
          „typ”: „wartość logiczna”,
          „domyślne”: fałsz,
          „description”: „Zmienna logiczna wskazująca, czy wykonać polecenie czyszczenia podczas inicjalizacji. Jeśli wartość wynosi true, polecenie czyszczenia nie zostanie wykonane po inicjalizacji. Jeśli wartość wynosi false, polecenie czyszczenia zostanie wykonane”.
        },
        „sesje”: {
          "$ref": "#/sesje"
        }
      },
      "wymagany": [
        "aktywny",
        „sesje”
      ]
    }
  },
  „sesje”: {
    „typ”: „obiekt”,
    „dodatkowe właściwości”: fałsz,
    „description”: „Lista sesji.”,
    "właściwościwzorca": {
      "domyślny": {
        "$ref": "#/sessionItem"
      },
      "^.*$": {
        "$ref": "#/sessionItem"
      }
    },
    "wymagany": [
      "domyślny"
    ]
  },
  "element sesji": {
    „typ”: „tablica”,
    „description”: „Element sesji.”,
    „min. elementy”: 1,
    „dodatkowe właściwości”: fałsz,
    "rzeczy": {
      "dowolny": [
        {
          "$ref": "#/terminalItem"
        },
        {
          „typ”: „tablica”,
          "rzeczy": {
            "$ref": "#/terminalItem"
          }
        }
      ]
    }
  },
  "element terminala": {
    „typ”: „obiekt”,
    „description”: „Element końcowy.”,
    "właściwości": {
      "nazwa": {
        „typ”: „ciąg”,
        „description”: „Czytelny dla człowieka ciąg znaków, który będzie używany do reprezentowania terminala w interfejsie użytkownika”.
      },
      "polecenia": {
        „typ”: „tablica”,
        „description”: „Lista poleceń.”,
        "rzeczy": {
          „typ”: „ciąg”,
          „description”: „Element polecenia”.
        }
      },
      "automatyczne wykonywanie poleceń": {
        „typ”: „wartość logiczna”,
        „domyślne”: fałsz,
        „description”: „Automatycznie wykonaj określone polecenia”.
      },
      "kolor": {
        "wyliczenie": [
          "terminal.ansiBlack",
          "terminal.ansiBlue",
          "terminal.ansiBrightBlack",
          "terminal.ansiBrightBlue",
          "terminal.ansiBrightCyan",
          "terminal.ansiBrightGreen",
          "terminal.ansiBrightMagenta",
          "terminal.ansiBrightRed",
          "terminal.ansiBrightWhite",
          "terminal.ansiBrightYellow",
          "terminal.ansiCyan",
          „terminal.ansiGreen”,
          "terminal.ansiMagenta",
          "terminal.ansiRed",
          "terminal.ansiWhite",
          „terminal.ansiYellow”
        ],
        „description”: „Identyfikator koloru. Dostępne kolory są wymienione w https://code.visualstudio.com/docs/getstarted/theme-color-reference”.
      },
      "cwd": {
        „typ”: „ciąg”,
        „description”: „Ścieżka lub Uri do bieżącego katalogu roboczego, który będzie używany w terminalu”.
      },
      "środowisko": {
        „typ”: „obiekt”,
        „dodatkowe właściwości”: fałsz,
        „description”: „Obiekt ze zmiennymi środowiskowymi, które zostaną dodane do procesu edytora.”,
        "właściwościwzorca": {
          "^.*$": {
            „typ”: „ciąg”
          }
        }
      },
      "ukryjOdUżytkownika": {
        „typ”: „wartość logiczna”,
        „description”: „Po włączeniu terminal uruchomi proces normalnie, ale nie będzie widoczny dla użytkownika do momentu wywołania Terminal.show. Typowe zastosowanie tej opcji to uruchamianie czegoś, co może wymagać interakcji, ale użytkownik chce zostać o tym poinformowany tylko wtedy, gdy interakcja jest konieczna. Należy pamiętać, że terminale nadal będą normalnie dostępne dla wszystkich rozszerzeń”.
      },
      "ikona": {
        "wyliczenie": [
          "konto",
          „ikona paska widoku kont”,
          „aktywuj punkty przerwania”,
          "dodać",
          "alarm",
          „archiwum”,
          "szyk",
          „strzałka-oba”,
          „strzałka-kółko-w-dół”,
          „strzałka-koło-lewo”,
          "arrow-circle-right",
          "arrow-circle-up",
          "arrow-down",
          "arrow-left",
          "arrow-right",
          "arrow-small-down",
          "arrow-small-left",
          "arrow-small-right",
          "arrow-small-up",
          "arrow-swap",
          "arrow-up",
          "azure-devops",
          "azure",
          "beaker-stop",
          "beaker",
          "bell-dot",
          "bell",
          "bold",
          "book",
          "bookmark",
          "bracket-dot",
          "bracket-error",
          "bracket",
          "breakpoints-activate",
          "breakpoints-remove-all",
          "breakpoints-view-icon",
          "briefcase",
          "broadcast",
          "browser",
          "bug",
          "calendar",
          "call-incoming",
          "call-outgoing",
          "callhierarchy-incoming",
          "callhierarchy-outgoing",
          "callstack-view-icon",
          "callstack-view-session",
          "case-sensitive",
          "check-all",
          "check",
          "checklist",
          "chevron-down",
          "chevron-left",
          "chevron-right",
          "chevron-up",
          "chrome-close",
          "chrome-maximize",
          "chrome-minimize",
          "chrome-restore",
          "circle-filled",
          "circle-large-filled",
          "circle-large-outline",
          "circle-outline",
          "circle-slash",
          "circuit-board",
          "clear-all",
          "clippy",
          "clock",
          "clone",
          "close-all",
          "close-dirty",
          "close",
          "cloud-download",
          "cloud-upload",
          "cloud",
          "code",
          "collapse-all",
          "color-mode",
          "combine",
          "comment-add",
          "comment-discussion",
          "comment",
          "comments-view-icon",
          "compare-changes",
          "compass-active",
          "compass-dot",
          "compass",
          "console",
          "credit-card",
          "dash",
          "dashboard",
          "database",
          "debug-all",
          "debug-alt-small",
          „debug-alt”,
          „debug-breakpoint-conditional-disabled”,
          „debug-breakpoint-conditional-unverified”,
          „debug-breakpoint-conditional”,
          „debug-breakpoint-data-disabled”,
          „debug-breakpoint-data-unverified”,
          „debug-breakpoint-data”,
          „debug-breakpoint-disabled”,
          „debug-breakpoint-function-disabled”,
          „funkcja punktu przerwania debugowania niezweryfikowana”,
          „funkcja-punktu-przerwania-debugowania”,
          „debug-breakpoint-log-disabled”,
          „debug-breakpoint-log-unverified”,
          „debug-breakpoint-log”,
          „debug-breakpoint-unsupported”,
          „debug-breakpoint-unverified”,
          „punkt przerwania debugowania”,
          „debug-collapse-all”,
          „debugowanie-konfigurowanie”,
          „debug-console-clear-all”,
          „debug-console-evaluation-input”,
          „monit oceny konsoli debugowania”,
          „debug-console-view-icon”,
          „debug-console”,
          „debug-continue-small”,
          „debugowanie-kontynuuj”,
          „pokrycie debugowania”,
          „debugowanie-rozłączanie”,
          „debug-gripper”,
          „wskazówka debugowania”,
          „debugowanie linia po linii”,
          „debug-pause”,
          „debug-rerun”,
          „ramka debugowania-restartu”,
          „debugowanie-restart”,
          „debugowanie-odwrócenie-kontynuowanie”,
          „debug-stackframe-active”,
          „debug-stackframe-dot”,
          „debug-stackframe-focused”,
          „debug-stackframe”,
          „debugowanie-start”,
          „debugowanie-krok-wstecz”,
          „debug-step-into”,
          „debug-step-out”,
          „debugowanie-krok-over”,
          „debug-stop”,
          "odpluskwić",
          „domyślna ikona widoku”,
          „pobieranie na pulpit”,
          „urządzenie-kamera-wideo”,
          „urządzenie-kamera”,
          „urządzenie-pulpit”,
          „urządzenie mobilne”,
          „diff-added”,
          „diff-editor-next-change”,
          „edytor różnic-poprzednia-zmiana”,
          "diff-editor-toggle-whitespace",
          „zignorowano różnicę”,
          „wstaw różnicę”,
          „modyfikowany różnicowo”,
          „usuń różnice”,
          „usunięto różnice”,
          „różnica-zmieniona nazwa”,
          „zamknij recenzję różnicową”,
          „wkładka z recenzją różnicową”,
          „różnica-przegląd-usuń”,
          "różnica",
          "wyrzucać",
          "redagować",
          „układ edytora”,
          "ellipsis",
          "empty-window",
          "error-small",
          "error",
          "exclude",
          "expand-all",
          "explorer-view-icon",
          "export",
          "extensions-clear-search-results",
          "extensions-configure-recommended",
          "extensions-filter",
          "extensions-info-message",
          "extensions-install-count",
          "extensions-install-local-in-remote",
          "extensions-install-workspace-recommended",
          "extensions-manage",
          "extensions-rating",
          "extensions-refresh",
          "extensions-remote",
          "extensions-star-empty",
          "extensions-star-full",
          "extensions-star-half",
          "extensions-sync-enabled",
          "extensions-sync-ignored",
          "extensions-view-icon",
          "extensions-warning-message",
          "extensions",
          "eye-closed",
          "eye-unwatch",
          "eye-watch",
          "eye",
          "feedback",
          "file-add",
          "file-binary",
          "file-code",
          "file-directory-create",
          "file-directory",
          "file-media",
          "file-pdf",
          "file-submodule",
          "file-symlink-directory",
          "file-symlink-file",
          "file-text",
          "file-zip",
          "file",
          "files",
          „wypełniony filtrem”,
          "filtr",
          „znajdź-zwiń”,
          „znajdź-rozszerzony”,
          „znajdź-następne-dopasowanie”,
          „znajdź-poprzednie-dopasowanie”,
          „znajdź-zamień-wszystko”,
          „znajdź-zamień”,
          „znajdź-wybór”,
          "płomień",
          "składany",
          "składany",
          "zginać",
          „folder aktywny”,
          „biblioteka folderów”,
          „otwarty folder”,
          "falcówka",
          „składany-złożony”,
          „składany-rozszerzony”,
          "zebrać",
          "bieg",
          „początkujący”
          „rozpoczęcie-konfiguracji”,
          "prezent",
          „widelec sedna”,
          „nowa istota”,
          „sedno prywatne”,
          „sekret-istoty”,
          "sens",
          „git-branch-create”,
          „git-branch-delete”,
          „git-branch”,
          „git-commit”,
          „git-porównaj”,
          „git-fork-prywatny”,
          „git-merge”,
          „git-pull-request-abandoned”,
          „git-pull-request-closed”,
          „git-pull-request-create”,
          „git-pull-request-draft”,
          „git-pull-request”,
          „github-action”,
          „github-alt”,
          „github-odwrócony”,
          „github”,
          "glob",
          „przejdź do pliku”,
          „przejdź do następnej lokalizacji”,
          „przejdź do poprzedniej lokalizacji”,
          "łapacz",
          „wykres-lewy”,
          "wykres-linia",
          „graf-rozrzut”,
          "wykres",
          "chwytak",
          „grupuj według typu odniesienia”,
          "serce",
          "historia",
          "dom",
          „zasada pozioma”,
          "hubot",
          „skrzynka odbiorcza”,
          "wciąć",
          „informacje”,
          "sprawdzać",
          „sprawa zamknięta”,
          „projekt wydania”,
          „problem otwarty”,
          „problem ponownie otwarty”,
          "kwestie",
          "italski",
          "golf",
          "json",
          "kebab-poziomy",
          "kebab-pionowy",
          "klawisz",
          „skróty klawiszowe-dodaj”,
          „edycja skrótów klawiszowych”,
          "skróty klawiszowe-nagrywanie-klawiszy",
          „skróty klawiszowe-sort”,
          "klawiatura",
          "prawo",
          „warstwy-aktywne”,
          „warstwy-kropka”,
          "layers",
          "layout-activitybar-left",
          "layout-activitybar-right",
          "layout-centered",
          "layout-menubar",
          "layout-panel-center",
          "layout-panel-justify",
          "layout-panel-left",
          "layout-panel-right",
          "layout-panel",
          "layout-sidebar-left",
          "layout-sidebar-right",
          "layout-statusbar",
          "layout",
          "library",
          "light-bulb",
          "lightbulb-autofix",
          "lightbulb",
          "link-external",
          "link",
          "list-filter",
          "list-flat",
          "list-ordered",
          "list-selection",
          "list-tree",
          "list-unordered",
          "live-share",
          "loaded-scripts-view-icon",
          "loading",
          "location",
          "lock-small",
          "lock",
          "log-in",
          "log-out",
          "logo-github",
          "magnet",
          "mail-read",
          "mail-reply",
          "mail",
          "mark-github",
          "markdown",
          "marker-navigation-next",
          "marker-navigation-previous",
          "markers-view-icon",
          "markers-view-multi-line-collapsed",
          "markers-view-multi-line-expanded",
          "megaphone",
          "mention",
          "menu",
          "merge",
          "microscope",
          "milestone",
          "mirror-private",
          "mirror-public",
          "mirror",
          "more",
          "mortar-board",
          "move",
          "multiple-windows",
          "mute",
          "new-file",
          "new-folder",
          "newline",
          "no-newline",
          "note",
          "notebook-clear",
          "notebook-collapsed",
          "notebook-delete-cell",
          "notebook-edit",
          "notebook-execute-all",
          "notebook-execute",
          "notebook-expanded",
          "notebook-kernel-select",
          "notebook-mimetype",
          "notebook-move-down",
          "notebook-move-up",
          "notebook-open-as-text",
          "notebook-render-output",
          "notebook-revert",
          "notebook-split-cell",
          "notebook-state-error",
          "notebook-state-success",
          "notebook-stop-edit",
          "notebook-stop",
          "notebook-template",
          "notebook",
          "notifications-clear-all",
          "notifications-clear",
          "notifications-collapse",
          "notifications-configure",
          "notifications-expand",
          "notifications-hide",
          "octoface",
          "open-editors-view-icon",
          "open-preview",
          "organization-filled",
          "organization-outline",
          "organization",
          "outline-view-icon",
          "output-view-icon",
          "output",
          "package",
          "paintcan",
          "panel-close",
          "panel-maximize",
          "panel-restore",
          "parameter-hints-next",
          "parameter-hints-previous",
          "pass-filled",
          "pass",
          "pencil",
          "person-add",
          "person-filled",
          "person-follow",
          "person-outline",
          "person",
          "pie-chart",
          "pin",
          "pinned-dirty",
          "pinned",
          "play-circle",
          "play",
          "plug",
          "plus",
          "ports-forward-icon",
          "ports-open-browser-icon",
          "ports-stop-forward-icon",
          "ports-view-icon",
          "preferences-clear-input",
          "preferences-open-settings",
          "preserve-case",
          "preview",
          "primitive-dot",
          "primitive-square",
          "private-ports-view-icon",
          "project",
          "pulse",
          "question",
          "quote",
          "radio-tower",
          "reactions",
          "record-keys",
          "record-small",
          "record",
          "redo",
          "refactor-preview-view-icon",
          "references",
          "refresh",
          "regex",
          "remote-explorer-documentation",
          "remote-explorer-feedback",
          "remote-explorer-get-started",
          "remote-explorer-report-issues",
          "remote-explorer-review-issues",
          "remote-explorer-view-icon",
          "remote-explorer",
          "remote",
          "remove-close",
          "remove",
          "repl",
          "replace-all",
          "replace",
          "reply",
          "repo-clone",
          "repo-create",
          "repo-delete",
          "repo-force-push",
          "repo-forked",
          "repo-pull",
          "repo-push",
          "repo-sync",
          "repo",
          "report",
          "request-changes",
          "review-comment-collapse",
          "rocket",
          "root-folder-opened",
          "root-folder",
          "rss",
          "ruby",
          "run-above",
          "run-all",
          "run-below",
          "run-errors",
          "run-view-icon",
          "run",
          "save-all",
          "save-as",
          "save",
          "screen-full",
          "screen-normal",
          "search-clear-results",
          "search-collapse-results",
          "search-details",
          "search-expand-results",
          "search-hide-replace",
          "search-new-editor",
          "search-refresh",
          "search-remove",
          "search-replace-all",
          "search-replace",
          "search-save",
          "search-show-context",
          "search-show-replace",
          "search-stop",
          "search-view-icon",
          "search",
          "selection",
          "server-environment",
          "server-process",
          "server",
          "settings-discard",
          "settings-edit",
          "settings-folder-dropdown",
          "settings-gear",
          "settings-more-action",
          "settings-remove",
          "settings-sync-view-icon",
          "settings-view-bar-icon",
          "settings",
          "shield",
          "sign-in",
          "sign-out",
          "smiley",
          "sort-precedence",
          "source-control-view-icon",
          "source-control",
          "split-horizontal",
          "split-vertical",
          "squirrel",
          "star-add",
          "star-delete",
          "star-empty",
          "star-full",
          "star-half",
          "star",
          "stop-circle",
          "stop",
          "suggest-more-info",
          "symbol-array",
          "symbol-boolean",
          "symbol-class",
          "symbol-color",
          "symbol-constant",
          "symbol-constructor",
          "symbol-enum-member",
          "symbol-enum",
          "symbol-event",
          "symbol-field",
          "symbol-file",
          "symbol-folder",
          "symbol-function",
          "symbol-interface",
          "symbol-key",
          "symbol-keyword",
          "symbol-method",
          "symbol-misc",
          "symbol-module",
          "symbol-namespace",
          "symbol-null",
          "symbol-number",
          "symbol-numeric",
          "symbol-object",
          "symbol-operator",
          "symbol-package",
          "symbol-parameter",
          "symbol-property",
          "symbol-reference",
          "symbol-ruler",
          "symbol-snippet",
          "symbol-string",
          "symbol-struct",
          "symbol-structure",
          "symbol-text",
          "symbol-type-parameter",
          "symbol-unit",
          "symbol-value",
          "symbol-variable",
          "sync-ignored",
          "sync",
          "tag-add",
          "tag-remove",
          "tag",
          "target",
          "tasklist",
          "tasks-list-configure",
          "tasks-remove",
          "telescope",
          "terminal-bash",
          "terminal-cmd",
          "terminal-debian",
          "terminal-kill",
          "terminal-linux",
          "terminal-new",
          "terminal-powershell",
          "terminal-rename",
          "terminal-tmux",
          "terminal-ubuntu",
          "terminal-view-icon",
          "terminal",
          "test-view-icon",
          "testing-cancel-icon",
          "testing-debug-icon",
          "testing-error-icon",
          "testing-failed-icon",
          "testing-passed-icon",
          "testing-queued-icon",
          "testing-run-all-icon",
          "testing-run-icon",
          "testing-show-as-list-icon",
          "testing-skipped-icon",
          "testing-unset-icon",
          "text-size",
          "three-bars",
          "thumbsdown",
          "thumbsup",
          "timeline-open",
          "timeline-pin",
          "timeline-refresh",
          "timeline-unpin",
          "timeline-view-icon",
          "tools",
          "trash",
          "trashcan",
          "triangle-down",
          "triangle-left",
          "triangle-right",
          "triangle-up",
          "twitter",
          "type-hierarchy-sub",
          "type-hierarchy-super",
          "type-hierarchy",
          "unfold",
          "ungroup-by-ref-type",
          "unlock",
          "unmute",
          "unverified",
          "variable",
          "variables-view-icon",
          "verified-filled",
          "verified",
          "versions",
          "view-pane-container-collapsed",
          "view-pane-container-expanded",
          "vm-active",
          "vm-connect",
          "vm-outline",
          "vm-running",
          "vm",
          "warning",
          "watch-expressions-add-function-breakpoint",
          "watch-expressions-add",
          "watch-expressions-remove-all",
          "watch-view-icon",
          "watch",
          "whitespace",
          "whole-word",
          "widget-close",
          "window",
          "word-wrap",
          "workspace-trusted",
          "workspace-untrusted",
          "wrench-subaction",
          "wrench",
          "x",
          "zap",
          "zoom-in",
          "zoom-out",
          "copilot",
          "git-fetch",
          "mic",
          "mic-filled",
          "coffee",
          "snake",
          "game",
          "vr",
          "chip",
          "piano",
          "music",
          "thumbsup-filled",
          "thumbsdown-filled"
        ],
        "description": "The id of the icon. The available icons are listed in https://code.visualstudio.com/api/references/icons-in-labels#icon-listing."
      },
      "isTransient": {
        "type": "boolean",
        "description": "Opt-out of the default terminal persistence on restart and reload. This will only take effect when terminal.integrated.enablePersistentSessions is enabled."
      },
      "message": {
        "type": "string",
        "description": "A message to write to the terminal on first launch, note that this is not sent to the process but, rather written directly to the terminal. This supports escape sequences such a setting text style"
      },
      "shellArgs": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Shell argument item."
        },
        "description": "Args for the custom shell executable. A string can be used on Windows only which allows specifying shell args in command-line format."
      },
      "shellPath": {
        "type": "string",
        "description": "A path to a custom shell executable to be used in the terminal."
      },
      "strictEnv": {
        "type": "boolean",
        "description": "Whether the terminal process environment should be exactly as provided in TerminalOptions.env. When this is false (default), the environment will be based on the window's environment and also apply configured platform settings like terminal.integrated.env.windows on top. When this is true, the complete environment must be provided as nothing will be inherited from the process or any configuration."
      },
      "joinOperator": {
        "type": "string",
        "default": ";",
        "description": "The operators to join multiple commands. e.g. semicolon (;), logical OR (||), logical AND (&&) and more"
      },
      "focus": {
        "type": "boolean",
        "description": "Focused the terminal on startup."
      },
      "disabled": {
        "type": "boolean",
        "description": "When true, this terminal will be disabled and not launched during an active session. Useful for temporarily turning off terminals without removing them."
      }
    },
    "required": [
      "name",
      "commands"
    ]
  }
}